### PR TITLE
Multisession support

### PR DESCRIPTION
**Pull request by aqasemi**
Hey. 

Please review this pr and tell me what do you think. I managed to make it run seamlessly with multiple devices/sessions at the same time and in one process. 

No breaking changes were introduced. One can either use the regular way to create clients (with `NewClient`) exactly as before this PR, or with the client factory `ClientFactory` and it will manage clients and events by itself.

### CODE REVIEW

**Comment by aqasemi** [comment]
#34

**Comment by aqasemi** [comment]
#33

**Comment by krypton-byte** [comment]
LGTM, I appreciate your pull request and you did a great job. I will merge your pull request as soon as possible.

Regarding this part:
```python
@staticmethod
def get_all_devices(db: str) -> List["Device"]:
```

Could the database data be retrieved from `self.database_name`?

Like this:
```python
def get_all_devices(self) -> List["Device"]:
    c_string = gocode.GetAllDevices(self.database_name).decode() 
    ...
```

Or, if it's better, could we rename the method to:
```python
@staticmethod
def get_all_devices_from_db(db: str) -> List["Device"]:
    c_string = gocode.GetAllDevices(db).decode()
```

Then, the implementation using `self.database_name` would be:
```python
def get_all_devices(self) -> List["Device"]:
    return self.get_all_devices_from_db(self.database_name)
```

**Comment by aqasemi** [comment]
thanks for the feedback. 
renamed to `get_all_devices_from_db` and removed the params although i thought maybe someone would need to read devices from multiple dbs. which was my case.

**Comment by aqasemi** [comment]
done. 
thanks for the feedback. 
I preferred the latter to easily read from multiple db files.

**Pull request merged**
